[package]
name = "thread_safe_var"
version = "0.1.0"
edition = "2024"

[dependencies]
parking_lot = { version = "0.12" }
rclite = { git = "https://github.com/NickGeek/rclite.git", rev = "b032369abf671ba3768a0eb59d01624438b5f4c1" }
thread_local = "1"
